//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory
    {
        public string SourceLanguage { get; set; }
        public string SourceText { get; set; }
        public string DestinationLanguage { get; set; }
        public string DestinationText { get; set; }
        public Nullable<int> UserID { get; set; }
        public int ID { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
